# Translations template for ironic.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the ironic project.
#
# Translators:
# Andrew_Melim <nokostya.translation@gmail.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Ironic\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-09-09 06:10+0000\n"
"PO-Revision-Date: 2014-07-21 23:13+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: French (http://www.transifex.com/projects/p/ironic/language/"
"fr/)\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: ironic/common/exception.py:79
msgid "Exception in string format operation"
msgstr ""

#: ironic/common/images.py:132
#, python-format
msgid "vfat image creation failed. Error: %s"
msgstr ""

#: ironic/common/images.py:200
msgid "Creating the filesystem root failed."
msgstr ""

#: ironic/common/images.py:214
msgid "Creating ISO image failed."
msgstr ""

#: ironic/common/service.py:88
#, python-format
msgid "Service error occurred when stopping the RPC server. Error: %s"
msgstr ""

#: ironic/common/service.py:93
#, python-format
msgid "Service error occurred when cleaning up the RPC manager. Error: %s"
msgstr ""

#: ironic/common/utils.py:414
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: ironic/common/glance_service/base_image_service.py:128
#, python-format
msgid ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"%(extra)s."
msgstr ""

#: ironic/dhcp/neutron.py:192
#, python-format
msgid "Failed to Get IP address on Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:208
#, python-format
msgid "Neutron returned invalid IPv4 address %s."
msgstr ""

#: ironic/dhcp/neutron.py:212
#, python-format
msgid "No IP address assigned to Neutron port %s."
msgstr ""

#: ironic/drivers/modules/agent.py:419
#, python-format
msgid "Async exception for %(node)s: %(msg)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:265
#, python-format
msgid ""
"IPMI get sensor data failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:416
#, python-format
msgid ""
"IPMI set boot device failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:451
#, python-format
msgid ""
"IPMI get boot device failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:295
#, python-format
msgid "Error returned from deploy ramdisk: %s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:308
#: ironic/drivers/modules/pxe.py:478 ironic/drivers/modules/ilo/deploy.py:454
#, python-format
msgid "Deploy failed for instance %(instance)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/pxe.py:290
msgid "UEFI boot mode is not supported with iPXE boot enabled."
msgstr ""

#: ironic/drivers/modules/pxe.py:455 ironic/drivers/modules/ilo/deploy.py:423
#, python-format
msgid "Node %s is not waiting to be deployed."
msgstr ""

#: ironic/drivers/modules/seamicro.py:551
#, python-format
msgid ""
"Seamicro set boot device failed for node %(node)s with the following error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ssh.py:654
#, python-format
msgid ""
"Failed to set boot device for node %(node)s, virt_type %(vtype)s does not "
"support this operation"
msgstr ""

#: ironic/drivers/modules/drac/management.py:78
#, python-format
msgid ""
"DRAC driver failed to get next boot mode for node %(node_uuid)s. Reason: "
"%(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:151
#, python-format
msgid ""
"DRAC driver failed to list the configuration jobs for node %(node_uuid)s. "
"Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:235
#, python-format
msgid ""
"DRAC driver failed to set the boot device for node %(node_uuid)s. Can't find "
"the ID for the %(device)s type. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:302
#, python-format
msgid ""
"DRAC driver failed to get the current boot device for node %(node_uuid)s. "
"Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/power.py:61
#, python-format
msgid ""
"DRAC driver failed to get power state for node %(node_uuid)s. Reason: "
"%(error)s."
msgstr ""

#: ironic/drivers/modules/drac/power.py:90
#: ironic/drivers/modules/drac/power.py:102
#, python-format
msgid ""
"DRAC driver failed to set power state for node %(node_uuid)s to "
"%(target_power_state)s. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:336
#, python-format
msgid ""
"Error while deleting %(object_name)s from %(container)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:346
#, python-format
msgid ""
"Error while ejecting virtual media %(device)s from node %(uuid)s. Error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:102
#, python-format
msgid ""
"Unable to find 'kernel_id' and 'ramdisk_id' in Glance image %(image)s for "
"generating boot ISO for %(node)s"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:143
#, python-format
msgid "Failed to clean up boot ISO for %(node)s.Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:436
#, python-format
msgid "Cannot get boot ISO for node %s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:298
#, python-format
msgid ""
"Failed to clean up the parameters on node %(node)s when unprovisioning the "
"instance %(instance)s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:607
#, python-format
msgid ""
"Error preparing deploy for instance %(instance)s on baremetal node %(node)s."
msgstr ""

#: ironic/nova/virt/ironic/driver.py:632
#, python-format
msgid "Error deploying instance %(instance)s on baremetal node %(node)s."
msgstr ""

#: ironic/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Exception d'origine en cours de suppression : %s"

#: ironic/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "Exception inattendue survenue %d fois... Nouvel essai."

#: ironic/openstack/common/lockutils.py:119
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: ironic/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "dans l'appel en boucle de dur√©e fixe"

#: ironic/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "dans l'appel en boucle dynamique"

#: ironic/openstack/common/periodic_task.py:202
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: ironic/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr ""

#: ironic/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr ""
