# Translations template for ironic.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the ironic project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: ironic 2015.2.0.dev332\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-07-09 06:23+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: ironic/api/controllers/base.py:102
#, python-format
msgid "Invalid value for %s header"
msgstr ""

#: ironic/api/controllers/v1/__init__.py:177
#, python-format
msgid ""
"Mutually exclusive versions requested. Version %(ver)s requested but not "
"supported by this service. The supported version range is: [%(min)s, "
"%(max)s]."
msgstr ""

#: ironic/api/controllers/v1/__init__.py:185
#, python-format
msgid ""
"Version %(ver)s was requested but the minor version is not supported by "
"this service. The supported version range is: [%(min)s, %(max)s]."
msgstr ""

#: ironic/api/controllers/v1/chassis.py:176
#: ironic/api/controllers/v1/node.py:825 ironic/api/controllers/v1/port.py:212
#, python-format
msgid "The sort_key value %(key)s is an invalid field for sorting"
msgstr ""

#: ironic/api/controllers/v1/node.py:407 ironic/conductor/manager.py:707
msgid "provisioning"
msgstr ""

#: ironic/api/controllers/v1/node.py:418
#, python-format
msgid "Adding a config drive is only supported when setting provision state to %s"
msgstr ""

#: ironic/api/controllers/v1/node.py:444
#, python-format
msgid "The requested action \"%(action)s\" could not be understood."
msgstr ""

#: ironic/api/controllers/v1/node.py:813
msgid "Chassis id not specified."
msgstr ""

#: ironic/api/controllers/v1/node.py:1012
#, python-format
msgid "Cannot create node with invalid name %(name)s"
msgstr ""

#: ironic/api/controllers/v1/node.py:1053
#, python-format
msgid "Node %s can not be updated while a state transition is in progress."
msgstr ""

#: ironic/api/controllers/v1/node.py:1063
#, python-format
msgid "Node %(node)s: Cannot change name to invalid name '%(name)s'"
msgstr ""

#: ironic/api/controllers/v1/node.py:1111
#, python-format
msgid ""
"Node %s can not update the driver while the console is enabled. Please "
"stop the console first."
msgstr ""

#: ironic/api/controllers/v1/port.py:200
msgid "Node identifier not specified."
msgstr ""

#: ironic/api/controllers/v1/types.py:174
#, python-format
msgid "%s is not JSON serializable"
msgstr ""

#: ironic/api/controllers/v1/types.py:256
#, python-format
msgid "'%s' is an internal attribute and can not be updated"
msgstr ""

#: ironic/api/controllers/v1/types.py:260
#, python-format
msgid "'%s' is a mandatory attribute and can not be removed"
msgstr ""

#: ironic/api/controllers/v1/types.py:265
msgid "'add' and 'replace' operations needs value"
msgstr ""

#: ironic/api/controllers/v1/utils.py:44
msgid "Limit must be positive"
msgstr ""

#: ironic/api/controllers/v1/utils.py:51
#, python-format
msgid "Invalid sort direction: %s. Acceptable values are 'asc' or 'desc'"
msgstr ""

#: ironic/api/controllers/v1/utils.py:61
#, python-format
msgid "Adding a new attribute (%s) to the root of  the resource is not allowed"
msgstr ""

#: ironic/api/controllers/v1/utils.py:141
msgid "Method not specified"
msgstr ""

#: ironic/api/controllers/v1/utils.py:185
#, python-format
msgid "Field(s) \"%s\" are not valid"
msgstr ""

#: ironic/api/controllers/v1/utils.py:210
#, python-format
msgid "Provision state \"%s\" is not valid"
msgstr ""

#: ironic/api/middleware/auth_token.py:44
#, python-format
msgid "Cannot compile public API routes: %s"
msgstr ""

#: ironic/api/middleware/parsable_error.py:52
#, python-format
msgid "ErrorDocumentMiddleware received an invalid status %s"
msgstr ""

#: ironic/common/disk_partitioner.py:167
#, python-format
msgid ""
"Disk partitioning failed on device %(device)s. Processes with the "
"following PIDs are holding it: %(pids)s. Time out waiting for completion."
msgstr ""

#: ironic/common/disk_partitioner.py:173
#, python-format
msgid ""
"Disk partitioning failed on device %(device)s. Fuser exited with "
"\"%(fuser_err)s\". Time out waiting for completion."
msgstr ""

#: ironic/common/exception.py:61
msgid "An unknown exception occurred."
msgstr ""

#: ironic/common/exception.py:109
msgid "Not authorized."
msgstr ""

#: ironic/common/exception.py:114
msgid "Operation not permitted."
msgstr ""

#: ironic/common/exception.py:118
msgid "Unacceptable parameters."
msgstr ""

#: ironic/common/exception.py:123
msgid "Conflict."
msgstr ""

#: ironic/common/exception.py:128
msgid "Resource temporarily unavailable, please retry."
msgstr ""

#: ironic/common/exception.py:134
msgid "Request not acceptable."
msgstr ""

#: ironic/common/exception.py:139
msgid "Invalid resource state."
msgstr ""

#: ironic/common/exception.py:143
#, python-format
msgid "A node with UUID %(uuid)s already exists."
msgstr ""

#: ironic/common/exception.py:147
#, python-format
msgid "A port with MAC address %(mac)s already exists."
msgstr ""

#: ironic/common/exception.py:151
#, python-format
msgid "A chassis with UUID %(uuid)s already exists."
msgstr ""

#: ironic/common/exception.py:155
#, python-format
msgid "A port with UUID %(uuid)s already exists."
msgstr ""

#: ironic/common/exception.py:159
#, python-format
msgid ""
"Instance %(instance_uuid)s is already associated with a node, it cannot "
"be associated with this other node %(node)s"
msgstr ""

#: ironic/common/exception.py:164
#, python-format
msgid "A node with name %(name)s already exists."
msgstr ""

#: ironic/common/exception.py:168
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr ""

#: ironic/common/exception.py:172
#, python-format
msgid "Expected a logical name or uuid but received %(name)s."
msgstr ""

#: ironic/common/exception.py:176
#, python-format
msgid "Expected a logical name but received %(name)s."
msgstr ""

#: ironic/common/exception.py:180
#, python-format
msgid "Expected an uuid or int but received %(identity)s."
msgstr ""

#: ironic/common/exception.py:184
#, python-format
msgid "Expected a MAC address but received %(mac)s."
msgstr ""

#: ironic/common/exception.py:188
#, python-format
msgid ""
"The requested action \"%(action)s\" can not be performed on node "
"\"%(node)s\" while it is in state \"%(state)s\"."
msgstr ""

#: ironic/common/exception.py:193
#, python-format
msgid "Couldn't apply patch '%(patch)s'. Reason: %(reason)s"
msgstr ""

#: ironic/common/exception.py:197
#, python-format
msgid "Failed to deploy instance: %(reason)s"
msgstr ""

#: ironic/common/exception.py:201 ironic/common/exception.py:205
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr ""

#: ironic/common/exception.py:211 ironic/common/exception.py:215
#, python-format
msgid "%(err)s"
msgstr ""

#: ironic/common/exception.py:219
msgid "Resource already exists."
msgstr ""

#: ironic/common/exception.py:223
msgid "Resource could not be found."
msgstr ""

#: ironic/common/exception.py:228
#, python-format
msgid "Failed to load DHCP provider %(dhcp_provider_name)s, reason: %(reason)s"
msgstr ""

#: ironic/common/exception.py:233
#, python-format
msgid "Could not find the following driver(s): %(driver_name)s."
msgstr ""

#: ironic/common/exception.py:237
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr ""

#: ironic/common/exception.py:241
#, python-format
msgid "No valid host was found. Reason: %(reason)s"
msgstr ""

#: ironic/common/exception.py:245
#, python-format
msgid "Instance %(instance)s could not be found."
msgstr ""

#: ironic/common/exception.py:249
#, python-format
msgid "Node %(node)s could not be found."
msgstr ""

#: ironic/common/exception.py:253
#, python-format
msgid "Node %(node)s is associated with instance %(instance)s."
msgstr ""

#: ironic/common/exception.py:257
#, python-format
msgid "Port %(port)s could not be found."
msgstr ""

#: ironic/common/exception.py:261
#, python-format
msgid "Update DHCP options on port: %(port_id)s failed."
msgstr ""

#: ironic/common/exception.py:265
#, python-format
msgid "Retrieve IP address on port: %(port_id)s failed."
msgstr ""

#: ironic/common/exception.py:269
#, python-format
msgid "Invalid IPv4 address %(ip_address)s."
msgstr ""

#: ironic/common/exception.py:273
#, python-format
msgid "Update MAC address on port: %(port_id)s failed."
msgstr ""

#: ironic/common/exception.py:277
#, python-format
msgid "Chassis %(chassis)s could not be found."
msgstr ""

#: ironic/common/exception.py:281
#, python-format
msgid "Conductor %(conductor)s cannot be started because no drivers were loaded."
msgstr ""

#: ironic/common/exception.py:286
#, python-format
msgid "Conductor %(conductor)s could not be found."
msgstr ""

#: ironic/common/exception.py:290
#, python-format
msgid "Conductor %(conductor)s already registered."
msgstr ""

#: ironic/common/exception.py:294
#, python-format
msgid "Failed to set node power state to %(pstate)s."
msgstr ""

#: ironic/common/exception.py:298
msgid "An exclusive lock is required, but the current context has a shared lock."
msgstr ""

#: ironic/common/exception.py:303
#, python-format
msgid "Failed to toggle maintenance-mode flag for node %(node)s: %(reason)s"
msgstr ""

#: ironic/common/exception.py:308
#, python-format
msgid "Console access is not enabled on node %(node)s"
msgstr ""

#: ironic/common/exception.py:312
#, python-format
msgid ""
"The %(op)s operation can't be performed on node %(node)s because it's in "
"maintenance mode."
msgstr ""

#: ironic/common/exception.py:317
#, python-format
msgid ""
"Cannot complete the requested action because chassis %(chassis)s contains"
" nodes."
msgstr ""

#: ironic/common/exception.py:322
#, python-format
msgid "IPMI call failed: %(cmd)s."
msgstr ""

#: ironic/common/exception.py:326
msgid "Failed to connect to AMT service."
msgstr ""

#: ironic/common/exception.py:330
#, python-format
msgid "AMT call failed: %(cmd)s."
msgstr ""

#: ironic/common/exception.py:334
msgid "MSFT OCS call failed."
msgstr ""

#: ironic/common/exception.py:338
#, python-format
msgid "Failed to establish SSH connection to host %(host)s."
msgstr ""

#: ironic/common/exception.py:342
#, python-format
msgid "Failed to execute command via SSH: %(cmd)s."
msgstr ""

#: ironic/common/exception.py:346
#, python-format
msgid "Unsupported object type %(objtype)s"
msgstr ""

#: ironic/common/exception.py:350
#, python-format
msgid "Cannot call %(method)s on orphaned %(objtype)s object"
msgstr ""

#: ironic/common/exception.py:354
#, python-format
msgid ""
"Driver %(driver)s does not support %(extension)s (disabled or not "
"implemented)."
msgstr ""

#: ironic/common/exception.py:359
#, python-format
msgid "Version %(objver)s of %(objname)s is not supported"
msgstr ""

#: ironic/common/exception.py:363
#, python-format
msgid "Connection to glance host %(host)s:%(port)s failed: %(reason)s"
msgstr ""

#: ironic/common/exception.py:368
#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr ""

#: ironic/common/exception.py:372
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr ""

#: ironic/common/exception.py:376
#, python-format
msgid "Validation of image href %(image_href)s failed, reason: %(reason)s"
msgstr ""

#: ironic/common/exception.py:381
#, python-format
msgid "Failed to download image %(image_href)s, reason: %(reason)s"
msgstr ""

#: ironic/common/exception.py:385
msgid "Not authorized in Keystone."
msgstr ""

#: ironic/common/exception.py:393
#, python-format
msgid ""
"Service type %(service_type)s with endpoint type %(endpoint_type)s not "
"found in keystone service catalog."
msgstr ""

#: ironic/common/exception.py:398
msgid "Connection failed"
msgstr ""

#: ironic/common/exception.py:402
msgid "Requested OpenStack Images API is forbidden"
msgstr ""

#: ironic/common/exception.py:410
msgid "The provided endpoint is invalid"
msgstr ""

#: ironic/common/exception.py:414
msgid "Unable to communicate with the server."
msgstr ""

#: ironic/common/exception.py:430
#, python-format
msgid "Could not find config at %(path)s"
msgstr ""

#: ironic/common/exception.py:434
#, python-format
msgid ""
"Node %(node)s is locked by host %(host)s, please retry after the current "
"operation is completed."
msgstr ""

#: ironic/common/exception.py:439
#, python-format
msgid "Node %(node)s found not to be locked on release"
msgstr ""

#: ironic/common/exception.py:443
msgid ""
"Requested action cannot be performed due to lack of free conductor "
"workers."
msgstr ""

#: ironic/common/exception.py:453
#, python-format
msgid "Invalid configuration file. %(error_msg)s"
msgstr ""

#: ironic/common/exception.py:457
#, python-format
msgid "Driver %(driver)s could not be loaded. Reason: %(reason)s."
msgstr ""

#: ironic/common/exception.py:465
#, python-format
msgid "Could not find pid in pid file %(pid_path)s"
msgstr ""

#: ironic/common/exception.py:469
#, python-format
msgid "Console subprocess failed to start. %(error)s"
msgstr ""

#: ironic/common/exception.py:473
#, python-format
msgid "Failed to create the password file. %(error)s"
msgstr ""

#: ironic/common/exception.py:481
#, python-format
msgid "%(operation)s failed, error: %(error)s"
msgstr ""

#: ironic/common/exception.py:485
#, python-format
msgid "%(operation)s not supported. error: %(error)s"
msgstr ""

#: ironic/common/exception.py:493
#, python-format
msgid ""
"DRAC client failed. Last error (cURL error code): %(last_error)s, fault "
"string: \"%(fault_string)s\" response_code: %(response_code)s"
msgstr ""

#: ironic/common/exception.py:500
#, python-format
msgid "DRAC operation failed. Message: %(message)s"
msgstr ""

#: ironic/common/exception.py:504
#, python-format
msgid ""
"DRAC operation yielded return value %(actual_return_value)s that is "
"neither error nor expected %(expected_return_value)s"
msgstr ""

#: ironic/common/exception.py:509
#, python-format
msgid ""
"Another job with ID %(job_id)s is already created  to configure "
"%(target)s. Wait until existing job is completed or is canceled"
msgstr ""

#: ironic/common/exception.py:515
#, python-format
msgid ""
"Invalid filter dialect '%(invalid_filter)s'. Supported options are "
"%(supported)s"
msgstr ""

#: ironic/common/exception.py:520
#, python-format
msgid "Failed to get sensor data for node %(node)s. Error: %(error)s"
msgstr ""

#: ironic/common/exception.py:525
#, python-format
msgid "Failed to parse sensor data for node %(node)s. Error: %(error)s"
msgstr ""

#: ironic/common/exception.py:530
#, python-format
msgid ""
"Disk volume where '%(path)s' is located doesn't have enough disk space. "
"Required %(required)d MiB, only %(actual)d MiB available space present."
msgstr ""

#: ironic/common/exception.py:536
#, python-format
msgid "Creating %(image_type)s image failed: %(error)s"
msgstr ""

#: ironic/common/exception.py:540
#, python-format
msgid "Swift operation '%(operation)s' failed: %(error)s"
msgstr ""

#: ironic/common/exception.py:544
#, python-format
msgid "SNMP operation '%(operation)s' failed: %(error)s"
msgstr ""

#: ironic/common/exception.py:548
#, python-format
msgid "Failed to create a file system. File system %(fs)s is not supported."
msgstr ""

#: ironic/common/exception.py:553
#, python-format
msgid "iRMC %(operation)s failed. Reason: %(error)s"
msgstr ""

#: ironic/common/exception.py:557
#, python-format
msgid "iRMC shared file system '%(share)s' is not mounted."
msgstr ""

#: ironic/common/exception.py:561
#, python-format
msgid "VirtualBox operation '%(operation)s' failed. Error: %(error)s"
msgstr ""

#: ironic/common/exception.py:566
#, python-format
msgid "Failed to inspect hardware. Reason: %(error)s"
msgstr ""

#: ironic/common/exception.py:570
#, python-format
msgid "Failed to clean node %(node)s: %(reason)s"
msgstr ""

#: ironic/common/exception.py:574
#, python-format
msgid "Path %(dir)s does not exist."
msgstr ""

#: ironic/common/exception.py:578
#, python-format
msgid "Directory %(dir)s is not writable."
msgstr ""

#: ironic/common/exception.py:582
#, python-format
msgid ""
"Cisco UCS client: operation %(operation)s failed for node %(node)s. "
"Reason: %(error)s"
msgstr ""

#: ironic/common/exception.py:587
#, python-format
msgid "Cisco UCS client: connection failed for node %(node)s. Reason: %(error)s"
msgstr ""

#: ironic/common/fsm.py:87
#, python-format
msgid "Target state '%s' does not exist"
msgstr ""

#: ironic/common/fsm.py:90
#, python-format
msgid "Target state '%s' is not a 'stable' state"
msgstr ""

#: ironic/common/hash_ring.py:86
msgid "Invalid hosts supplied when building HashRing."
msgstr ""

#: ironic/common/hash_ring.py:117
msgid "Invalid data supplied to HashRing.get_hosts."
msgstr ""

#: ironic/common/hash_ring.py:200
#, python-format
msgid "The driver '%s' is unknown."
msgstr ""

#: ironic/common/image_service.py:142
#, python-format
msgid "Got HTTP code %s instead of 200 in response to HEAD request."
msgstr ""

#: ironic/common/image_service.py:165
#, python-format
msgid "Got HTTP code %s instead of 200 in response to GET request."
msgstr ""

#: ironic/common/image_service.py:188
msgid ""
"Cannot determine image size as there is no Content-Length header "
"specified in response to HEAD request."
msgstr ""

#: ironic/common/image_service.py:212
msgid "Specified image file not found."
msgstr ""

#: ironic/common/image_service.py:288
#, python-format
msgid "Image download protocol %s is not supported."
msgstr ""

#: ironic/common/images.py:357
msgid "'qemu-img info' parsing failed."
msgstr ""

#: ironic/common/images.py:364
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr ""

#: ironic/common/images.py:379
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr ""

#: ironic/common/images.py:562
msgid "Deploy iso didn't contain efiboot.img or grub.cfg"
msgstr ""

#: ironic/common/keystone.py:51
msgid "Keystone API endpoint is missing"
msgstr ""

#: ironic/common/keystone.py:75
#, python-format
msgid "Could not authorize in Keystone: %s"
msgstr ""

#: ironic/common/keystone.py:110
msgid "No Keystone service catalog loaded"
msgstr ""

#: ironic/common/pxe_utils.py:111
#, python-format
msgid "Failed to get IP address for any port on node %s."
msgstr ""

#: ironic/common/swift.py:100
msgid "put container"
msgstr ""

#: ironic/common/swift.py:111
msgid "put object"
msgstr ""

#: ironic/common/swift.py:131
msgid "head account"
msgstr ""

#: ironic/common/swift.py:159
msgid "delete object"
msgstr ""

#: ironic/common/swift.py:175
msgid "head object"
msgstr ""

#: ironic/common/swift.py:190
msgid "post object"
msgstr ""

#: ironic/common/utils.py:118
msgid "Invalid private key"
msgstr ""

#: ironic/common/utils.py:638
#, python-format
msgid ""
"Cannot update capabilities. The new capabilities should be in a "
"dictionary. Provided value is %s"
msgstr ""

#: ironic/common/utils.py:651
#, python-format
msgid "Invalid capabilities string '%s'."
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:139
#, python-format
msgid "The given image info does not have a valid image id: %s"
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:165
msgid ""
"Swift temporary URLs require a shared secret to be created. You must "
"provide \"swift_temp_url_key\" as a config option."
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:169
msgid ""
"Swift temporary URLs require a Swift endpoint URL. You must provide "
"\"swift_endpoint_url\" as a config option."
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:173
msgid ""
"Swift temporary URLs require a Swift account string. You must provide "
"\"swift_account\" as a config option."
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:177
msgid "\"swift_temp_url_duration\" must be a positive integer."
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:182
msgid ""
"An integer value between 0 and 32 is required for "
"swift_store_multiple_containers_seed."
msgstr ""

#: ironic/conductor/manager.py:298
#, python-format
msgid "The deployment can't be resumed by conductor %s. Moving to fail state."
msgstr ""

#: ironic/conductor/manager.py:501 ironic/conductor/manager.py:600
#: ironic/drivers/utils.py:85
#, python-format
msgid "No handler for method %s"
msgstr ""

#: ironic/conductor/manager.py:506 ironic/conductor/manager.py:605
#, python-format
msgid "The method %(method)s does not support HTTP %(http)s"
msgstr ""

#: ironic/conductor/manager.py:742
#, python-format
msgid "RPC do_node_deploy failed to validate deploy or power info. Error: %(msg)s"
msgstr ""

#: ironic/conductor/manager.py:790
#, python-format
msgid ""
"Failed to validate power driver interface. Can not delete instance. "
"Error: %(msg)s"
msgstr ""

#: ironic/conductor/manager.py:815
#, python-format
msgid "Failed to tear down. Error: %s"
msgstr ""

#: ironic/conductor/manager.py:864
#, python-format
msgid ""
"Cannot continue cleaning on %(node)s, node is in %(state)s state, should "
"be %(clean_state)s"
msgstr ""

#: ironic/conductor/manager.py:900
#, python-format
msgid ""
"Failed to validate power driver interface. Can not clean node %(node)s. "
"Error: %(msg)s"
msgstr ""

#: ironic/conductor/manager.py:910
#, python-format
msgid "Failed to prepare node %(node)s for cleaning: %(e)s"
msgstr ""

#: ironic/conductor/manager.py:943
#, python-format
msgid "Node %(node)s got an invalid last step for %(state)s: %(step)s."
msgstr ""

#: ironic/conductor/manager.py:965
#, python-format
msgid "Node %(node)s failed step %(step)s: %(exc)s"
msgstr ""

#: ironic/conductor/manager.py:984
#, python-format
msgid ""
"While executing step %(step)s on node %(node)s, step returned invalid "
"value: %(val)s"
msgstr ""

#: ironic/conductor/manager.py:1000
#, python-format
msgid "Failed to tear down from cleaning for node %s"
msgstr ""

#: ironic/conductor/manager.py:1276
msgid "not supported"
msgstr ""

#: ironic/conductor/manager.py:1325
#, python-format
msgid ""
"Can not delete node \"%(node)s\" while it is in provision state "
"\"%(state)s\". Valid provision states to perform deletion are: "
"\"%(valid_states)s\""
msgstr ""

#: ironic/conductor/manager.py:1432
msgid "enabled"
msgstr ""

#: ironic/conductor/manager.py:1432
msgid "disabled"
msgstr ""

#: ironic/conductor/manager.py:1455
msgid "enabling"
msgstr ""

#: ironic/conductor/manager.py:1455
msgid "disabling"
msgstr ""

#: ironic/conductor/manager.py:1456
#, python-format
msgid "Error %(op)s the console on node %(node)s. Reason: %(error)s"
msgstr ""

#: ironic/conductor/manager.py:1738
#, python-format
msgid ""
"RPC inspect_hardware failed to validate inspection or power info. Error: "
"%(msg)s"
msgstr ""

#: ironic/conductor/manager.py:1770
msgid "timeout reached while inspecting the node"
msgstr ""

#: ironic/conductor/manager.py:1856 ironic/conductor/manager.py:1884
msgid "No free conductor workers available"
msgstr ""

#: ironic/conductor/manager.py:1957
#, python-format
msgid "Failed to upload the configdrive to Swift. Error: %s"
msgstr ""

#: ironic/conductor/manager.py:1968
#, python-format
msgid "Failed to prepare to deploy. Error: %s"
msgstr ""

#: ironic/conductor/manager.py:1977
#, python-format
msgid "Failed to deploy. Error: %s"
msgstr ""

#: ironic/conductor/manager.py:2013
#, python-format
msgid ""
"During sync_power_state, max retries exceeded for node %(node)s, node "
"state %(actual)s does not match expected state '%(state)s'. Updating DB "
"state to '%(actual)s' Switching node to maintenance mode."
msgstr ""

#: ironic/conductor/manager.py:2060
msgid "Power driver returned ERROR state while trying to sync power state."
msgstr ""

#: ironic/conductor/manager.py:2155
#, python-format
msgid "During inspection, driver returned unexpected state %(state)s"
msgstr ""

#: ironic/conductor/rpcapi.py:112
#, python-format
msgid "No conductor service registered which supports driver %s."
msgstr ""

#: ironic/conductor/utils.py:71 ironic/conductor/utils.py:118
#, python-format
msgid "Failed to change power state to '%(target)s'. Error: %(error)s"
msgstr ""

#: ironic/conductor/utils.py:139
#, python-format
msgid "Timeout reached while waiting for callback for node %s"
msgstr ""

#: ironic/conductor/utils.py:145
#, python-format
msgid "Cleanup failed for node %(node)s after deploy timeout:  %(error)s"
msgstr ""

#: ironic/conductor/utils.py:157
msgid ""
"Deploy timed out, but an unhandled exception was encountered while "
"aborting. More info may be found in the log file."
msgstr ""

#: ironic/db/sqlalchemy/api.py:148
#, python-format
msgid "The sort_key value \"%(key)s\" is an invalid field for sorting"
msgstr ""

#: ironic/db/sqlalchemy/api.py:339
msgid "Cannot overwrite UUID for an existing Node."
msgstr ""

#: ironic/db/sqlalchemy/api.py:436
msgid "Cannot overwrite UUID for an existing Port."
msgstr ""

#: ironic/db/sqlalchemy/api.py:494
msgid "Cannot overwrite UUID for an existing Chassis."
msgstr ""

#: ironic/dhcp/neutron.py:74
msgid "Neutron auth_strategy should be either \"noauth\" or \"keystone\"."
msgstr ""

#: ironic/dhcp/neutron.py:171
#, python-format
msgid ""
"No VIFs found for node %(node)s when attempting to update DHCP BOOT "
"options."
msgstr ""

#: ironic/dhcp/neutron.py:185
#, python-format
msgid "Failed to set DHCP BOOT options for any port on node %s."
msgstr ""

#: ironic/dhcp/neutron.py:297
msgid "Valid cleaning network UUID not provided"
msgstr ""

#: ironic/dhcp/neutron.py:313
#, python-format
msgid "Could not create cleaning port on network %(net)s from %(node)s. %(exc)s"
msgstr ""

#: ironic/dhcp/neutron.py:322
#, python-format
msgid "Failed to create cleaning ports for node %(node)s"
msgstr ""

#: ironic/dhcp/neutron.py:343
#, python-format
msgid ""
"Could not get cleaning network vif for %(node)s from Neutron, possible "
"network issue. %(exc)s"
msgstr ""

#: ironic/dhcp/neutron.py:357
#, python-format
msgid ""
"Could not remove cleaning ports on network %(net)s from %(node)s, "
"possible network issue. %(exc)s"
msgstr ""

#: ironic/drivers/agent.py:105 ironic/drivers/fake.py:211
#: ironic/drivers/pxe.py:249
msgid "Unable to import pyremotevbox library"
msgstr ""

#: ironic/drivers/agent.py:127 ironic/drivers/fake.py:261
#: ironic/drivers/pxe.py:308
msgid "Unable to import UcsSdk library"
msgstr ""

#: ironic/drivers/drac.py:35 ironic/drivers/fake.py:172
#: ironic/drivers/fake.py:239 ironic/drivers/pxe.py:269
msgid "Unable to import pywsman library"
msgstr ""

#: ironic/drivers/fake.py:108
msgid "Unable to import pyghmi IPMI library"
msgstr ""

#: ironic/drivers/fake.py:122 ironic/drivers/pxe.py:131
msgid "Unable to import seamicroclient library"
msgstr ""

#: ironic/drivers/fake.py:146 ironic/drivers/pxe.py:159
msgid "Unable to import iboot library"
msgstr ""

#: ironic/drivers/fake.py:158 ironic/drivers/ilo.py:43 ironic/drivers/ilo.py:67
#: ironic/drivers/pxe.py:179
msgid "Unable to import proliantutils library"
msgstr ""

#: ironic/drivers/fake.py:186 ironic/drivers/pxe.py:202
msgid "Unable to import pysnmp library"
msgstr ""

#: ironic/drivers/fake.py:198 ironic/drivers/irmc.py:44
#: ironic/drivers/irmc.py:67 ironic/drivers/pxe.py:225
msgid "Unable to import python-scciclient library"
msgstr ""

#: ironic/drivers/pxe.py:106
msgid "Unable to import pyghmi library"
msgstr ""

#: ironic/drivers/utils.py:79
msgid "Method not specified when calling vendor extension."
msgstr ""

#: ironic/drivers/modules/agent.py:81 ironic/drivers/modules/pxe.py:103
msgid "UUID (from Glance) of the deployment kernel. Required."
msgstr ""

#: ironic/drivers/modules/agent.py:83
msgid ""
"UUID (from Glance) of the ramdisk with agent that is used at deploy time."
" Required."
msgstr ""

#: ironic/drivers/modules/agent.py:271
#, python-format
msgid "Node %s failed to validate deploy image info. Some parameters were missing"
msgstr ""

#: ironic/drivers/modules/agent.py:277
#, python-format
msgid ""
"image_source's image_checksum must be provided in instance_info for node "
"%s"
msgstr ""

#: ironic/drivers/modules/agent.py:285
#, python-format
msgid ""
"Node %(node)s is configured to use the %(driver)s driver which currently "
"does not support deploying partition images."
msgstr ""

#: ironic/drivers/modules/agent.py:498
#, python-format
msgid "node %(node)s command status errored: %(error)s"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:134
msgid "Missing parameter version"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:137
#, python-format
msgid "Unknown lookup payload version: %s"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:172
#, python-format
msgid "Agent returned error for clean step %(step)s on node %(node)s : %(err)s."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:187
#, python-format
msgid "Could not restart cleaning on node %(node)s: %(err)s."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:201
#, python-format
msgid ""
"Agent returned unknown status for clean step %(step)s on node %(node)s : "
"%(err)s."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:232
msgid "For heartbeat operation, \"agent_url\" must be specified."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:241
msgid "Failed checking if deploy is done."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:249
msgid "Node failed to get image for deploy."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:253
msgid "Node failed to move to active state."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:267
#, python-format
msgid "Asynchronous exception for node %(node)s: %(msg)s exception: %(e)s"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:365
#, python-format
msgid "Malformed network interfaces lookup: %s"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:394
#, python-format
msgid "No ports matching the given MAC addresses %sexist in the database."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:442
#, python-format
msgid ""
"Ports matching mac addresses match multiple nodes. MACs: %(macs)s. Port "
"ids: %(port_ids)s"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:496
#, python-format
msgid "Error rebooting node %(node)s after deploy. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:530
#, python-format
msgid ""
"Failed to install a bootloader when deploying node %(node)s. Error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:539
#, python-format
msgid ""
"Failed to change the boot device to %(boot_dev)s when deploying node "
"%(node)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/agent_client.py:49
msgid "Agent driver requires agent_url in driver_internal_info"
msgstr ""

#: ironic/drivers/modules/agent_client.py:76
#, python-format
msgid ""
"Unable to decode response as JSON.\n"
"Request URL: %(url)s\n"
"Request body: \"%(body)s\"\n"
"Response: \"%(response)s\""
msgstr ""

#: ironic/drivers/modules/console_utils.py:84
#, python-format
msgid ""
"Cannot create directory '%(path)s' for console PID file. Reason: "
"%(reason)s."
msgstr ""

#: ironic/drivers/modules/console_utils.py:207
#, python-format
msgid ""
"%(exec_error)s\n"
"Command: %(command)s"
msgstr ""

#: ironic/drivers/modules/console_utils.py:224
#, python-format
msgid ""
"Command: %(command)s.\n"
"Exit code: %(return_code)s.\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: ironic/drivers/modules/console_utils.py:237
#, python-format
msgid "Timeout while waiting for console subprocessto start for node %s."
msgstr ""

#: ironic/drivers/modules/console_utils.py:264
#, python-format
msgid "Could not stop the console for node '%(node)s'. Reason: %(err)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:136
#, python-format
msgid ""
"iSCSI connection was not seen by the file system after attempting to "
"verify %d times."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:160
#, python-format
msgid ""
"iSCSI connection did not become active after attempting to verify %d "
"times."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:312
#, python-format
msgid ""
"Unable to stat device %(dev)s after attempting to verify %(attempts)d "
"times."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:516
#, python-format
msgid ""
"Can't download the configdrive content for node %(node)s from '%(url)s'. "
"Reason: %(reason)s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:525
#, python-format
msgid ""
"Config drive for node %s is not base64 encoded or the content is "
"malformed."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:528
#, python-format
msgid " Downloaded from \"%s\"."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:542
#, python-format
msgid ""
"Encountered error while decompressing and writing config drive for node "
"%(node)s. Error: %(exc)s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:613
#, python-format
msgid "Root device '%s' not found"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:623
#, python-format
msgid "'%(partition)s' device '%(part_device)s' not found"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:704
#: ironic/drivers/modules/iscsi_deploy.py:242
#, python-format
msgid ""
"Root partition is too small for requested image. Image virtual size: "
"%(image_mb)d MB, Root size: %(root_mb)d MB"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:754
#, python-format
msgid "Parent device '%s' not found"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:805
#, python-format
msgid "%(error_msg)s. Missing are: %(missing_info)s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:899
#, python-format
msgid ""
"Error parsing capabilities from Node %s instance_info field. A dictionary"
" or a \"jsonified\" dictionary is expected."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:933
#, python-format
msgid "get_clean_steps for node %(node)s returned invalid result: %(result)s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:969
#, python-format
msgid "Agent on node %(node)s returned bad command result: %(result)s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:1042
#, python-format
msgid ""
"The hints \"%(invalid_hints)s\" are invalid. Valid hints are: "
"\"%(valid_hints)s\""
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:1052
msgid "Root device hint \"size\" is not an integer value."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:1156
#, python-format
msgid ""
"The parameter '%(capability)s' from %(field)s has an invalid value: "
"'%(value)s'. Acceptable values are: %(valid_values)s."
msgstr ""

#: ironic/drivers/modules/fake.py:49
#, python-format
msgid "set_power_state called with an invalid powerstate: %s."
msgstr ""

#: ironic/drivers/modules/fake.py:119
msgid "Parameter 'bar' not passed to method 'first_method'."
msgstr ""

#: ironic/drivers/modules/fake.py:123
msgid "Test if the value of bar is baz"
msgstr ""

#: ironic/drivers/modules/fake.py:139
#, python-format
msgid "Parameter 'bar' not passed to method '%s'."
msgstr ""

#: ironic/drivers/modules/fake.py:143
msgid "Test if the value of bar is kazoo"
msgstr ""

#: ironic/drivers/modules/fake.py:148
msgid "Test if the value of bar is meow"
msgstr ""

#: ironic/drivers/modules/fake.py:186 ironic/drivers/modules/ipminative.py:409
#: ironic/drivers/modules/ipmitool.py:821
#: ironic/drivers/modules/seamicro.py:571 ironic/drivers/modules/ssh.py:656
#: ironic/drivers/modules/virtualbox.py:339
#: ironic/drivers/modules/ilo/management.py:201
#: ironic/drivers/modules/irmc/management.py:142
#, python-format
msgid "Invalid boot device %s specified."
msgstr ""

#: ironic/drivers/modules/iboot.py:38
msgid "IP address of the node. Required."
msgstr ""

#: ironic/drivers/modules/iboot.py:39 ironic/drivers/modules/seamicro.py:71
msgid "username. Required."
msgstr ""

#: ironic/drivers/modules/iboot.py:40 ironic/drivers/modules/seamicro.py:69
msgid "password. Required."
msgstr ""

#: ironic/drivers/modules/iboot.py:43
msgid "iBoot PDU relay id; default is 1. Optional."
msgstr ""

#: ironic/drivers/modules/iboot.py:44
msgid "iBoot PDU port; default is 9100. Optional."
msgstr ""

#: ironic/drivers/modules/iboot.py:55
#, python-format
msgid "Missing the following iBoot credentials in node's driver_info: %s."
msgstr ""

#: ironic/drivers/modules/iboot.py:67
msgid "iBoot PDU relay id must be an integer."
msgstr ""

#: ironic/drivers/modules/iboot.py:74
msgid "iBoot PDU port must be an integer."
msgstr ""

#: ironic/drivers/modules/iboot.py:108
#, python-format
msgid "Cannot get power status for node '%(node)s'. iBoot get_relays() failed."
msgstr ""

#: ironic/drivers/modules/iboot.py:186 ironic/drivers/modules/ipmitool.py:739
#: ironic/drivers/modules/snmp.py:672 ironic/drivers/modules/ssh.py:573
#, python-format
msgid "set_power_state called with invalid power state %s."
msgstr ""

#: ironic/drivers/modules/inspector.py:82
msgid "ironic-inspector support is disabled"
msgstr ""

#: ironic/drivers/modules/inspector.py:86
msgid "python-ironic-inspector-client Python module not found"
msgstr ""

#: ironic/drivers/modules/inspector.py:165
#, python-format
msgid "Failed to start inspection: %s"
msgstr ""

#: ironic/drivers/modules/inspector.py:199
#, python-format
msgid "ironic-inspector inspection failed: %s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:67
msgid "IP of the node's BMC. Required."
msgstr ""

#: ironic/drivers/modules/ipminative.py:68
msgid "IPMI password. Required."
msgstr ""

#: ironic/drivers/modules/ipminative.py:69
msgid "IPMI username. Required."
msgstr ""

#: ironic/drivers/modules/ipminative.py:72
#: ironic/drivers/modules/ipmitool.py:101 ironic/drivers/modules/seamicro.py:80
#: ironic/drivers/modules/ilo/common.py:74
msgid "node's UDP port to connect to. Only required for console access."
msgstr ""

#: ironic/drivers/modules/ipminative.py:96
#: ironic/drivers/modules/ipmitool.py:243
#, python-format
msgid "Missing the following IPMI credentials in node's driver_info: %s."
msgstr ""

#: ironic/drivers/modules/ipminative.py:114
#: ironic/drivers/modules/ipmitool.py:271
msgid "IPMI terminal port is not an integer."
msgstr ""

#: ironic/drivers/modules/ipminative.py:344
#, python-format
msgid "set_power_state called with an invalid power state: %s."
msgstr ""

#: ironic/drivers/modules/ipminative.py:499
#: ironic/drivers/modules/ipmitool.py:1040
msgid "Missing 'ipmi_terminal_port' parameter in node's driver_info."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:73
msgid "IP address or hostname of the node. Required."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:76
msgid "password. Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:77
#, python-format
msgid "privilege level; default is ADMINISTRATOR. One of %s. Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:79
msgid "username; default is NULL user. Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:80
msgid ""
"bridging_type; default is \"no\". One of \"single\", \"dual\", \"no\". "
"Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:82
msgid ""
"transit channel for bridged request. Required only if ipmi_bridging is "
"set to \"dual\"."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:84
msgid ""
"transit address for bridged request. Required only if ipmi_bridging is "
"set to \"dual\"."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:86
msgid ""
"destination channel for bridged request. Required only if ipmi_bridging "
"is set to \"single\" or \"dual\"."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:89
msgid ""
"destination address for bridged request. Required only if ipmi_bridging "
"is set to \"single\" or \"dual\"."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:92
msgid ""
"local IPMB address for bridged requests. Used only if ipmi_bridging is "
"set to \"single\" or \"dual\". Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:95
msgid ""
"the version of the IPMI protocol; default is \"2.0\". One of \"1.5\", "
"\"2.0\". Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:262
#, python-format
msgid ""
"Invalid IPMI protocol version value %(version)s, the valid value can be "
"one of %(valid_versions)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:282
#, python-format
msgid ""
"Value for ipmi_bridging is provided as %s, but IPMI bridging is not "
"supported by the IPMI utility installed on host. Ensure ipmitool version "
"is > 1.8.11"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:305
#, python-format
msgid "%(param)s not provided"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:308
#, python-format
msgid ""
"Invalid value for ipmi_bridging: %(bridging_type)s, the valid value can "
"be one of: %(bridging_types)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:316
#, python-format
msgid ""
"Invalid privilege level value:%(priv_level)s, the valid value can be one "
"of %(valid_levels)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:577
#, python-format
msgid "parse ipmi sensor data failed, unknown sensor type data: %(sensors_data)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:617
#, python-format
msgid ""
"parse ipmi sensor data failed, get nothing with input data: "
"%(sensors_data)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:664
#, python-format
msgid ""
"Ipmitool drivers need to be able to create temporary files to pass "
"password to ipmitool. Encountered error: %s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:682
#: ironic/drivers/modules/ipmitool.py:775
#: ironic/drivers/modules/ipmitool.py:928
#: ironic/drivers/modules/ipmitool.py:1021
msgid ""
"Unable to locate usable ipmitool command in the system path when checking"
" ipmitool version"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:1005
msgid "Parameter raw_bytes (string of bytes) was not specified."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:1045
msgid ""
"Serial over lan only works with IPMI protocol version 2.0. Check the "
"'ipmi_protocol_version' parameter in node's driver_info"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:125
#, python-format
msgid ""
" Deployed value of %(param)s was %(param_value)s but requested value is "
"%(request_value)s."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:131
#, python-format
msgid ""
"The following parameters have different values from previous "
"deployment:%(error_msg)s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:181
msgid ""
"Cannot validate iSCSI deploy. Some parameters were missing in node's "
"instance_info"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:190
#, python-format
msgid ""
"Cannot validate parameter for iSCSI deploy. Invalid parameter %(param)s. "
"Reason: %(reason)s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:196
#, python-format
msgid "%s is not an integer value."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:203
msgid "Cannot deploy whole disk image with swap or ephemeral size set"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:296
msgid "Deploy key does not match"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:318
#, python-format
msgid "Parameters %s were not passed to ironic for deploy."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:364
#, python-format
msgid "Error returned from deploy ramdisk: %s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:385
#, python-format
msgid "Deploy failed for instance %(instance)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:393
#, python-format
msgid ""
"Couldn't determine the UUID of the root partition or the disk identifier "
"after deploying node %s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:436
#, python-format
msgid ""
"Failed to start the iSCSI target to deploy the node %(node)s. Error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:567
#, python-format
msgid "Failed to connect to Glance to get the properties of the image %s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:571
#, python-format
msgid "Image %s can not be found."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:583
#, python-format
msgid "Image %(image)s is missing the following properties: %(properties)s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:604 ironic/drivers/modules/ssh.py:519
#, python-format
msgid "Node %s does not have any port associated with it."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:613
#, python-format
msgid ""
"Couldn't get the URL of the Ironic API service from the configuration "
"file or keystone catalog. Keystone error: %s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:636
msgid ""
"Some mandatory input missing in 'pass_bootloader_info' vendor passthru "
"from ramdisk."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:643
#, python-format
msgid "Deploy key %(key_sent)s does not match with %(expected_key)s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:662
#, python-format
msgid "Failed to install bootloader on node %(node)s. Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:689
#, python-format
msgid ""
"Failed to notify ramdisk to reboot after bootloader installation. Error: "
"%s"
msgstr ""

#: ironic/drivers/modules/pxe.py:105
msgid "UUID (from Glance) of the ramdisk that is mounted at boot time. Required."
msgstr ""

#: ironic/drivers/modules/pxe.py:124
msgid ""
"Cannot validate PXE bootloader. Some parameters were missing in node's "
"driver_info"
msgstr ""

#: ironic/drivers/modules/pxe.py:223
#, python-format
msgid ""
"Conflict: Whole disk image being used for deploy, but cannot be used with"
" node %(node_uuid)s configured to use UEFI boot with netboot option"
msgstr ""

#: ironic/drivers/modules/pxe.py:240
#, python-format
msgid ""
"Trusted boot is only supported in BIOS boot mode with netboot and without"
" whole_disk_image, but Node %(node_uuid)s was configured with boot_mode: "
"%(boot_mode)s, boot_option: %(boot_option)s, is_whole_disk_image: "
"%(is_whole_disk_image)s: at least one of them is wrong, and this can be "
"caused by enable secure boot."
msgstr ""

#: ironic/drivers/modules/pxe.py:333
msgid "iPXE boot is enabled but no HTTP URL or HTTP root was specified."
msgstr ""

#: ironic/drivers/modules/pxe.py:340
#, python-format
msgid ""
"Conflict: iPXE is enabled, but cannot be used with node%(node_uuid)s "
"configured to use UEFI boot"
msgstr ""

#: ironic/drivers/modules/pxe.py:622 ironic/drivers/modules/ilo/deploy.py:892
#: ironic/drivers/modules/irmc/deploy.py:845
msgid "Failed to continue iSCSI deployment."
msgstr ""

#: ironic/drivers/modules/seamicro.py:68
msgid "API endpoint. Required."
msgstr ""

#: ironic/drivers/modules/seamicro.py:70
msgid "server ID. Required."
msgstr ""

#: ironic/drivers/modules/seamicro.py:74
msgid "version of SeaMicro API client; default is 2. Optional."
msgstr ""

#: ironic/drivers/modules/seamicro.py:101
#, python-format
msgid "Invalid 'seamicro_api_version' parameter. Reason: %s."
msgstr ""

#: ironic/drivers/modules/seamicro.py:117
#, python-format
msgid ""
"SeaMicro driver requires the following parameters to be set in node's "
"driver_info: %s."
msgstr ""

#: ironic/drivers/modules/seamicro.py:132
msgid "SeaMicro terminal port is not an integer."
msgstr ""

#: ironic/drivers/modules/seamicro.py:137
msgid ""
"Invalid 'seamicro_server_id' parameter in node's driver_info. Expected "
"format of 'seamicro_server_id' is <int>/<int>"
msgstr ""

#: ironic/drivers/modules/seamicro.py:144
msgid "Invalid 'seamicro_api_endpoint' parameter in node's driver_info."
msgstr ""

#: ironic/drivers/modules/seamicro.py:339
msgid "Invalid volume id specified"
msgstr ""

#: ironic/drivers/modules/seamicro.py:355
msgid "No storage pools found for ironic"
msgstr ""

#: ironic/drivers/modules/seamicro.py:425
msgid "set_power_state called with invalid power state."
msgstr ""

#: ironic/drivers/modules/seamicro.py:466
msgid "No vlan id provided"
msgstr ""

#: ironic/drivers/modules/seamicro.py:507
msgid "No volume size provided for creating volume"
msgstr ""

#: ironic/drivers/modules/seamicro.py:633
msgid "Missing 'seamicro_terminal_port' parameter in node's driver_info"
msgstr ""

#: ironic/drivers/modules/snmp.py:73
msgid "PDU manufacturer driver.  Required."
msgstr ""

#: ironic/drivers/modules/snmp.py:74
msgid "PDU IPv4 address or hostname.  Required."
msgstr ""

#: ironic/drivers/modules/snmp.py:75
msgid "PDU power outlet index (1-based).  Required."
msgstr ""

#: ironic/drivers/modules/snmp.py:79
#, python-format
msgid "SNMP protocol version: %(v1)s, %(v2c)s, %(v3)s  (optional, default %(v1)s)"
msgstr ""

#: ironic/drivers/modules/snmp.py:83
#, python-format
msgid "SNMP port, default %(port)d"
msgstr ""

#: ironic/drivers/modules/snmp.py:85
#, python-format
msgid "SNMP community.  Required for versions %(v1)s, %(v2c)s"
msgstr ""

#: ironic/drivers/modules/snmp.py:88
#, python-format
msgid "SNMP security name.  Required for version %(v3)s"
msgstr ""

#: ironic/drivers/modules/snmp.py:547
#, python-format
msgid ""
"SNMP driver requires the following parameters to be set in node's "
"driver_info: %s."
msgstr ""

#: ironic/drivers/modules/snmp.py:556
#, python-format
msgid "SNMPPowerDriver: unknown driver: '%s'"
msgstr ""

#: ironic/drivers/modules/snmp.py:562
#, python-format
msgid "SNMPPowerDriver: unknown SNMP version: '%s'"
msgstr ""

#: ironic/drivers/modules/snmp.py:571
#, python-format
msgid "SNMPPowerDriver: SNMP UDP port must be numeric: %s"
msgstr ""

#: ironic/drivers/modules/snmp.py:574
#, python-format
msgid "SNMPPowerDriver: SNMP UDP port out of range: %d"
msgstr ""

#: ironic/drivers/modules/snmp.py:581
#, python-format
msgid "SNMP driver requires snmp_community to be set for version %s."
msgstr ""

#: ironic/drivers/modules/snmp.py:587
#, python-format
msgid "SNMP driver requires snmp_security to be set for version %s."
msgstr ""

#: ironic/drivers/modules/ssh.py:58
msgid "IP address or hostname of the node to ssh into. Required."
msgstr ""

#: ironic/drivers/modules/ssh.py:60
msgid "username to authenticate as. Required."
msgstr ""

#: ironic/drivers/modules/ssh.py:61
msgid ""
"virtualization software to use; one of vbox, virsh, vmware, parallels. "
"Required."
msgstr ""

#: ironic/drivers/modules/ssh.py:65
msgid ""
"private key(s). One of this, ssh_key_filename, or ssh_password must be "
"specified."
msgstr ""

#: ironic/drivers/modules/ssh.py:67
msgid ""
"(list of) filename(s) of optional private key(s) for authentication. One "
"of this, ssh_key_contents, or ssh_password must be specified."
msgstr ""

#: ironic/drivers/modules/ssh.py:70
msgid ""
"password to use for authentication or for unlocking a private key. One of"
" this, ssh_key_contents, or ssh_key_filename must be specified."
msgstr ""

#: ironic/drivers/modules/ssh.py:73
msgid "port on the node to connect to; default is 22. Optional."
msgstr ""

#: ironic/drivers/modules/ssh.py:105
#, python-format
msgid "SSHPowerDriver '%(virt_type)s' is not a valid virt_type."
msgstr ""

#: ironic/drivers/modules/ssh.py:206
#, python-format
msgid "SSHPowerDriver '%(virt_type)s' is not a valid virt_type, "
msgstr ""

#: ironic/drivers/modules/ssh.py:297
#, python-format
msgid ""
"SSHPowerDriver requires the following parameters to be set in node's "
"driver_info: %s."
msgstr ""

#: ironic/drivers/modules/ssh.py:307
msgid "SSHPowerDriver requires ssh_port to be integer value"
msgstr ""

#: ironic/drivers/modules/ssh.py:328
msgid ""
"SSHPowerDriver requires one and only one of password, key_contents and "
"key_filename to be set."
msgstr ""

#: ironic/drivers/modules/ssh.py:337
#, python-format
msgid "SSH key file %s not found."
msgstr ""

#: ironic/drivers/modules/ssh.py:524
#, python-format
msgid "SSH connection cannot be established: %s"
msgstr ""

#: ironic/drivers/modules/virtualbox.py:59
msgid "Name of the VM in VirtualBox. Required."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:60
msgid "IP address or hostname of the VirtualBox host. Required."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:65
msgid "Username for the VirtualBox host. Default value is ''. Optional."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:67
msgid "Password for 'virtualbox_username'. Default value is ''. Optional."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:69
msgid "Port on which VirtualBox web service is listening. Optional."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:111
#, python-format
msgid "The following parameters are missing in driver_info: %s"
msgstr ""

#: ironic/drivers/modules/virtualbox.py:123
msgid "'virtualbox_port' is not an integer."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:169
#, python-format
msgid "Invalid VirtualMachine method '%s' passed to '_run_virtualbox_method'."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:245
#, python-format
msgid "'set_power_state' called with invalid power state '%s'"
msgstr ""

#: ironic/drivers/modules/wol.py:37
msgid "Broadcast IP address; defaults to 255.255.255.255. Optional."
msgstr ""

#: ironic/drivers/modules/wol.py:39
msgid "Destination port; defaults to 9. Optional."
msgstr ""

#: ironic/drivers/modules/wol.py:73
#, python-format
msgid ""
"Failed to send Wake-On-Lan magic packets to node %(node)s port %(port)s. "
"Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/wol.py:91
msgid "Wake-On-Lan port must be an integer"
msgstr ""

#: ironic/drivers/modules/wol.py:95
msgid "Wake-On-Lan needs at least one port resource to be registered in the node"
msgstr ""

#: ironic/drivers/modules/wol.py:162
#, python-format
msgid ""
"set_power_state called for Node %(node)s with invalid power state "
"%(pstate)s."
msgstr ""

#: ironic/drivers/modules/amt/common.py:37
msgid "IP address or host name of the node. Required."
msgstr ""

#: ironic/drivers/modules/amt/common.py:38
msgid "Password. Required."
msgstr ""

#: ironic/drivers/modules/amt/common.py:39
msgid "Username to log into AMT system. Required."
msgstr ""

#: ironic/drivers/modules/amt/common.py:42
msgid ""
"Protocol used for AMT endpoint. one of http, https; default is \"http\". "
"Optional."
msgstr ""

#: ironic/drivers/modules/amt/common.py:161
#, python-format
msgid "AMT driver requires the following to be set in node's driver_info: %s."
msgstr ""

#: ironic/drivers/modules/amt/common.py:170
#, python-format
msgid "Invalid protocol %s."
msgstr ""

#: ironic/drivers/modules/amt/management.py:192
#: ironic/drivers/modules/msftocs/management.py:67
#, python-format
msgid ""
"set_boot_device called with invalid device %(device)s for node "
"%(node_id)s."
msgstr ""

#: ironic/drivers/modules/amt/power.py:165
#: ironic/drivers/modules/msftocs/power.py:85
#, python-format
msgid "Unsupported target_state: %s"
msgstr ""

#: ironic/drivers/modules/drac/common.py:26
msgid "IP address or hostname of the DRAC card. Required."
msgstr ""

#: ironic/drivers/modules/drac/common.py:27
msgid "username used for authentication. Required."
msgstr ""

#: ironic/drivers/modules/drac/common.py:28
msgid "password used for authentication. Required."
msgstr ""

#: ironic/drivers/modules/drac/common.py:31
msgid "port used for WS-Man endpoint; default is 443. Optional."
msgstr ""

#: ironic/drivers/modules/drac/common.py:32
msgid "path used for WS-Man endpoint; default is \"/wsman\". Optional."
msgstr ""

#: ironic/drivers/modules/drac/common.py:34
msgid ""
"protocol used for WS-Man endpoint; one of http, https; default is "
"\"https\". Optional."
msgstr ""

#: ironic/drivers/modules/drac/common.py:61
#, python-format
msgid "'%s' not supplied to DracDriver."
msgstr ""

#: ironic/drivers/modules/drac/common.py:63
#, python-format
msgid "'%s' contains non-ASCII symbol."
msgstr ""

#: ironic/drivers/modules/drac/common.py:71
msgid "'drac_path' contains non-ASCII symbol."
msgstr ""

#: ironic/drivers/modules/drac/common.py:77
msgid "'drac_protocol' contains non-ASCII symbol."
msgstr ""

#: ironic/drivers/modules/drac/common.py:82
msgid "'drac_port' is not an integer value."
msgstr ""

#: ironic/drivers/modules/drac/common.py:85
#, python-format
msgid ""
"The following errors were encountered while parsing driver_info:\n"
"%s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:64
msgid "IP address or hostname of the iLO. Required."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:65
msgid "username for the iLO with administrator privileges. Required."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:67
msgid "password for ilo_username. Required."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:70
msgid "port to be used for iLO operations. Optional."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:71
msgid "timeout (in seconds) for iLO operations. Optional."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:78
msgid ""
"new password for iLO. Required if the clean step 'reset_ilo_credential' "
"is enabled."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:114
#, python-format
msgid ""
"The following required iLO parameters are missing from the node's "
"driver_info: %s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:135
#, python-format
msgid ""
"The following iLO parameters from the node's driver_info should be "
"integers: %s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:183
msgid "iLO license check"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:280
#, python-format
msgid "Inserting virtual media %s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:310
#: ironic/drivers/modules/ilo/common.py:359
#, python-format
msgid "Setting %s as boot mode"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:435
#, python-format
msgid "Eject virtual media %s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:477
#, python-format
msgid "Get secure boot mode for node %s."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:510
#, python-format
msgid "Setting secure boot to %(flag)s for node %(node)s."
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:59
msgid "UUID (from Glance) of the deployment ISO. Required."
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:216
msgid ""
"Error validating iLO virtual media deploy. Some parameters were missing "
"in node's driver_info"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:711
msgid "Missing 'console_port' parameter in node's driver_info."
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:758
#, python-format
msgid ""
"The requested action 'boot_into_iso' can be performed only when node "
"%(node_uuid)s is in %(state)s state or in 'maintenance' mode"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:765
msgid ""
"Error validating input for boot_into_iso vendor passthru. Some parameters"
" were not provided: "
msgstr ""

#: ironic/drivers/modules/ilo/inspect.py:101
#, python-format
msgid "Server didn't return the key(s): %(key)s"
msgstr ""

#: ironic/drivers/modules/ilo/inspect.py:106
#, python-format
msgid ""
"Essential properties are expected to be in dictionary format, received "
"%(properties)s from node %(node)s."
msgstr ""

#: ironic/drivers/modules/ilo/inspect.py:112
#, python-format
msgid "The node %s didn't return 'properties' as the key with inspection."
msgstr ""

#: ironic/drivers/modules/ilo/inspect.py:118
#, python-format
msgid "Node %(node)s didn't return MACs %(macs)s in dictionary format."
msgstr ""

#: ironic/drivers/modules/ilo/inspect.py:123
#, python-format
msgid "The node %s didn't return 'macs' as the key with inspection."
msgstr ""

#: ironic/drivers/modules/ilo/inspect.py:203
#, python-format
msgid "Inspecting hardware (get_power_state) on %s"
msgstr ""

#: ironic/drivers/modules/ilo/management.py:93
#, python-format
msgid "Clean step '%s' not found. 'proliantutils' package needs to be updated."
msgstr ""

#: ironic/drivers/modules/ilo/management.py:104
#, python-format
msgid "Clean step %(step)s failed on node %(node)s with error: %(err)s"
msgstr ""

#: ironic/drivers/modules/ilo/management.py:169
msgid "Get boot device"
msgstr ""

#: ironic/drivers/modules/ilo/management.py:212
#, python-format
msgid "Setting %s as boot device"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:97
msgid "iLO get_power_status"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:161
#: ironic/drivers/modules/irmc/power.py:88
#, python-format
msgid "_set_power_state called with invalid power state '%s'"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:170
msgid "iLO set_power_state"
msgstr ""

#: ironic/drivers/modules/irmc/common.py:50
msgid "IP address or hostname of the iRMC. Required."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:51
msgid "Username for the iRMC with administrator privileges. Required."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:53
msgid "Password for irmc_username. Required."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:56
msgid ""
"Port to be used for iRMC operations; either 80 or 443. The default value "
"is 443. Optional."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:58
msgid ""
"Authentication method for iRMC operations; either 'basic' or 'digest'. "
"The default value is 'basic'. Optional."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:61
msgid ""
"Timeout (in seconds) for iRMC operations. The default value is 60. "
"Optional."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:63
msgid ""
"Sensor data retrieval method; either 'ipmitool' or 'scci'. The default "
"value is 'ipmitool'. Optional."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:89
#, python-format
msgid "Missing the following iRMC parameters in node's driver_info: %s."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:103
msgid "'irmc_auth_method' has unsupported value."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:106
msgid "'irmc_port' has unsupported value."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:109
msgid "'irmc_client_timeout' is not integer type."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:112
msgid "'irmc_sensor_method' has unsupported value."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:114
#, python-format
msgid ""
"The following type errors were encountered while parsing driver_info:\n"
"%s"
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:78
msgid "Deployment ISO image file name. Required."
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:98
#, python-format
msgid "Value '%s' for remote_image_share_root isn't a directory or doesn't exist."
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:103
#, python-format
msgid ""
"Value '%s' for remote_image_share_type is not supported value either "
"'NFS' or 'CIFS'."
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:107
#, python-format
msgid "The following errors were encountered while parsing config file:%s"
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:130
msgid ""
"Error validating iRMC virtual media deploy. Some parameters were missing "
"in node's driver_info"
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:139
#: ironic/tests/drivers/irmc/test_deploy.py:133
#, python-format
msgid "Deploy ISO file, %(deploy_iso)s, not found for node: %(node)s."
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:171
#: ironic/tests/drivers/irmc/test_deploy.py:230
#, python-format
msgid "Boot ISO file, %(boot_iso)s, not found for node: %(node)s."
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:343
msgid "Copying floppy image file"
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:431
msgid "Inserting virtual cdrom"
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:454
msgid "Ejecting virtual cdrom"
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:487
msgid "Inserting virtual floppy"
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:510
msgid "Ejecting virtual floppy"
msgstr ""

#: ironic/drivers/modules/irmc/power.py:97
msgid "iRMC set_power_state"
msgstr ""

#: ironic/drivers/modules/msftocs/common.py:26
msgid ""
"Base url of the OCS chassis manager REST API, e.g.: http://10.0.0.1:8000."
" Required."
msgstr ""

#: ironic/drivers/modules/msftocs/common.py:28
msgid ""
"Blade id, must be a number between 1 and the maximum number of blades "
"available in the chassis. Required."
msgstr ""

#: ironic/drivers/modules/msftocs/common.py:31
msgid "Username to access the chassis manager REST API. Required."
msgstr ""

#: ironic/drivers/modules/msftocs/common.py:33
msgid "Password to access the chassis manager REST API. Required."
msgstr ""

#: ironic/drivers/modules/msftocs/common.py:81
#, python-format
msgid "The following parameters were missing: %s"
msgstr ""

#: ironic/drivers/modules/msftocs/common.py:99
#, python-format
msgid "\"%s\" is not a valid \"msftocs_base_url\""
msgstr ""

#: ironic/drivers/modules/msftocs/common.py:106
#, python-format
msgid "\"%s\" is not a valid \"msftocs_blade_id\""
msgstr ""

#: ironic/drivers/modules/msftocs/common.py:109
#, python-format
msgid "\"msftocs_blade_id\" must be greater than 0. The provided value is: %s"
msgstr ""

#: ironic/drivers/modules/msftocs/msftocsclient.py:74
#, python-format
msgid "HTTP call failed: %s"
msgstr ""

#: ironic/drivers/modules/msftocs/msftocsclient.py:87
#, python-format
msgid "Invalid XML: %s"
msgstr ""

#: ironic/drivers/modules/msftocs/msftocsclient.py:91
#, python-format
msgid "Operation failed: %s"
msgstr ""

#: ironic/drivers/modules/ucs/helper.py:35
msgid "IP or Hostname of the UCS Manager. Required."
msgstr ""

#: ironic/drivers/modules/ucs/helper.py:36
msgid "UCS Manager admin/server-profile username. Required."
msgstr ""

#: ironic/drivers/modules/ucs/helper.py:37
msgid "UCS Manager password. Required."
msgstr ""

#: ironic/drivers/modules/ucs/helper.py:38
msgid "UCS Manager service-profile name. Required."
msgstr ""

#: ironic/drivers/modules/ucs/helper.py:81
#, python-format
msgid "%s driver requires these parameters to be set in the node's driver_info."
msgstr ""

#: ironic/drivers/modules/ucs/management.py:97
msgid "setting boot device"
msgstr ""

#: ironic/drivers/modules/ucs/management.py:131
msgid "getting boot device"
msgstr ""

#: ironic/drivers/modules/ucs/power.py:129
msgid "getting power status"
msgstr ""

#: ironic/drivers/modules/ucs/power.py:154
#, python-format
msgid "set_power_state called with invalid power state '%s'"
msgstr ""

#: ironic/drivers/modules/ucs/power.py:171
msgid "setting power status"
msgstr ""

#: ironic/drivers/modules/ucs/power.py:203
msgid "rebooting"
msgstr ""

#: ironic/objects/base.py:158
msgid "Invalid version string"
msgstr ""

#: ironic/objects/base.py:347
#, python-format
msgid "Cannot load '%(attrname)s' in the base class"
msgstr ""

#: ironic/objects/base.py:356
msgid "Cannot save anything in the base class"
msgstr ""

#: ironic/objects/base.py:388
#, python-format
msgid "%(objname)s object has no attribute '%(attrname)s'"
msgstr ""

#: ironic/objects/conductor.py:56
msgid "Cannot update a conductor record directly."
msgstr ""

#: ironic/objects/utils.py:40
msgid "A datetime.datetime is required here"
msgstr ""

#: ironic/objects/utils.py:105
#, python-format
msgid "An object of class %s is required here"
msgstr ""

#: ironic/openstack/common/imageutils.py:76
#, python-format
msgid "Invalid input value \"%s\"."
msgstr ""

#: ironic/openstack/common/imageutils.py:105
msgid "Snapshot list encountered but no header found!"
msgstr ""

